# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseFormatsGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addTypes(object):
    def setupUi(self, addTypes):
        addTypes.setObjectName(_fromUtf8("addTypes"))
        addTypes.resize(439, 587)
        self.centralwidget = QtGui.QWidget(addTypes)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageTypeCB = QtGui.QComboBox(self.centralwidget)
        self.imageTypeCB.setGeometry(QtCore.QRect(118, 10, 221, 27))
        self.imageTypeCB.setObjectName(_fromUtf8("imageTypeCB"))
        self.startTrack = QtGui.QLineEdit(self.centralwidget)
        self.startTrack.setGeometry(QtCore.QRect(118, 60, 61, 27))
        self.startTrack.setObjectName(_fromUtf8("startTrack"))
        self.endTrack = QtGui.QLineEdit(self.centralwidget)
        self.endTrack.setGeometry(QtCore.QRect(277, 59, 61, 27))
        self.endTrack.setObjectName(_fromUtf8("endTrack"))
        self.sideModeCB = QtGui.QComboBox(self.centralwidget)
        self.sideModeCB.setGeometry(QtCore.QRect(118, 100, 221, 27))
        self.sideModeCB.setObjectName(_fromUtf8("sideModeCB"))
        self.sectorSizeCB = QtGui.QComboBox(self.centralwidget)
        self.sectorSizeCB.setGeometry(QtCore.QRect(118, 140, 221, 27))
        self.sectorSizeCB.setObjectName(_fromUtf8("sectorSizeCB"))
        self.sectorCountCB = QtGui.QComboBox(self.centralwidget)
        self.sectorCountCB.setGeometry(QtCore.QRect(118, 177, 101, 27))
        self.sectorCountCB.setObjectName(_fromUtf8("sectorCountCB"))
        self.sectorCount = QtGui.QLineEdit(self.centralwidget)
        self.sectorCount.setGeometry(QtCore.QRect(248, 177, 41, 27))
        self.sectorCount.setObjectName(_fromUtf8("sectorCount"))
        self.trackDistanceCB = QtGui.QComboBox(self.centralwidget)
        self.trackDistanceCB.setGeometry(QtCore.QRect(118, 217, 221, 27))
        self.trackDistanceCB.setObjectName(_fromUtf8("trackDistanceCB"))
        self.flippyMode = QtGui.QCheckBox(self.centralwidget)
        self.flippyMode.setGeometry(QtCore.QRect(131, 295, 121, 22))
        self.flippyMode.setObjectName(_fromUtf8("flippyMode"))
        self.tracksDefault = QtGui.QCheckBox(self.centralwidget)
        self.tracksDefault.setEnabled(True)
        self.tracksDefault.setGeometry(QtCore.QRect(350, 62, 99, 22))
        self.tracksDefault.setChecked(True)
        self.tracksDefault.setObjectName(_fromUtf8("tracksDefault"))
        self.sideModeDefault = QtGui.QCheckBox(self.centralwidget)
        self.sideModeDefault.setGeometry(QtCore.QRect(350, 103, 99, 22))
        self.sideModeDefault.setChecked(True)
        self.sideModeDefault.setObjectName(_fromUtf8("sideModeDefault"))
        self.sectorSizeDefault = QtGui.QCheckBox(self.centralwidget)
        self.sectorSizeDefault.setGeometry(QtCore.QRect(349, 143, 99, 22))
        self.sectorSizeDefault.setChecked(True)
        self.sectorSizeDefault.setObjectName(_fromUtf8("sectorSizeDefault"))
        self.sectorCountDefault = QtGui.QCheckBox(self.centralwidget)
        self.sectorCountDefault.setGeometry(QtCore.QRect(349, 180, 99, 22))
        self.sectorCountDefault.setChecked(True)
        self.sectorCountDefault.setObjectName(_fromUtf8("sectorCountDefault"))
        self.trackDistanceDefault = QtGui.QCheckBox(self.centralwidget)
        self.trackDistanceDefault.setGeometry(QtCore.QRect(349, 217, 99, 22))
        self.trackDistanceDefault.setChecked(True)
        self.trackDistanceDefault.setObjectName(_fromUtf8("trackDistanceDefault"))
        self.addType = QtGui.QPushButton(self.centralwidget)
        self.addType.setGeometry(QtCore.QRect(259, 290, 171, 31))
        self.addType.setObjectName(_fromUtf8("addType"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(29, 12, 81, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(29, 62, 81, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(205, 62, 71, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(31, 104, 81, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(29, 143, 81, 20))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(19, 180, 91, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(9, 220, 101, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(24, 260, 81, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.targetRPMDefault = QtGui.QCheckBox(self.centralwidget)
        self.targetRPMDefault.setGeometry(QtCore.QRect(350, 258, 99, 22))
        self.targetRPMDefault.setChecked(True)
        self.targetRPMDefault.setObjectName(_fromUtf8("targetRPMDefault"))
        self.settingsDisplay = QtGui.QTextBrowser(self.centralwidget)
        self.settingsDisplay.setGeometry(QtCore.QRect(10, 370, 421, 171))
        self.settingsDisplay.setObjectName(_fromUtf8("settingsDisplay"))
        self.resetTypes = QtGui.QPushButton(self.centralwidget)
        self.resetTypes.setGeometry(QtCore.QRect(330, 338, 99, 27))
        self.resetTypes.setObjectName(_fromUtf8("resetTypes"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(12, 350, 181, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.targetRPMCB = QtGui.QComboBox(self.centralwidget)
        self.targetRPMCB.setGeometry(QtCore.QRect(118, 255, 221, 27))
        self.targetRPMCB.setObjectName(_fromUtf8("targetRPMCB"))
        addTypes.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(addTypes)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 439, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        addTypes.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(addTypes)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        addTypes.setStatusBar(self.statusbar)

        self.retranslateUi(addTypes)
        QtCore.QObject.connect(self.resetTypes, QtCore.SIGNAL(_fromUtf8("clicked()")), addTypes.reset_types)
        QtCore.QObject.connect(self.addType, QtCore.SIGNAL(_fromUtf8("clicked()")), addTypes.save_and_add)
        QtCore.QObject.connect(self.tracksDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.tracks_default_change)
        QtCore.QObject.connect(self.sideModeDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.side_mode_default_change)
        QtCore.QObject.connect(self.sectorSizeDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.sector_size_default_change)
        QtCore.QObject.connect(self.sectorCountDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.sector_count_default_change)
        QtCore.QObject.connect(self.trackDistanceDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.track_distance_default_change)
        QtCore.QObject.connect(self.targetRPMDefault, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.target_RPM_default_change)
        QtCore.QObject.connect(self.flippyMode, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), addTypes.flippy_change)
        QtCore.QMetaObject.connectSlotsByName(addTypes)

    def retranslateUi(self, addTypes):
        addTypes.setWindowTitle(_translate("addTypes", "Add Disk Types", None))
        self.flippyMode.setText(_translate("addTypes", "Flippy Mode", None))
        self.tracksDefault.setText(_translate("addTypes", "Default", None))
        self.sideModeDefault.setText(_translate("addTypes", "Default", None))
        self.sectorSizeDefault.setText(_translate("addTypes", "Default", None))
        self.sectorCountDefault.setText(_translate("addTypes", "Default", None))
        self.trackDistanceDefault.setText(_translate("addTypes", "Default", None))
        self.addType.setText(_translate("addTypes", "Save (and add another)", None))
        self.label.setText(_translate("addTypes", "Image Type", None))
        self.label_2.setText(_translate("addTypes", "Start Track", None))
        self.label_3.setText(_translate("addTypes", "End Track", None))
        self.label_4.setText(_translate("addTypes", "Side Mode", None))
        self.label_5.setText(_translate("addTypes", "Sector Size", None))
        self.label_6.setText(_translate("addTypes", "Sector Count", None))
        self.label_7.setText(_translate("addTypes", "Track distance", None))
        self.label_8.setText(_translate("addTypes", "Target RPM", None))
        self.targetRPMDefault.setText(_translate("addTypes", "Default", None))
        self.resetTypes.setText(_translate("addTypes", "Reset all", None))
        self.label_9.setText(_translate("addTypes", "Configured image types:", None))

